article/urls.py
from django.urls import path
from article import views

urlpatterns = [
    path('all', views.ArticleListView.as_view(), name='article_list'),
    path('article_detail/<slug:slug>', views.ArticleDetailView.as_view(), name='article_detail'),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from article.views import HomePageView
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path("robots.txt",
         TemplateView.as_view(template_name="robots.txt",
                              content_type="text/plain")
         ),
]

urlpatterns += i18n_patterns(
    path('', HomePageView.as_view(), name='home'),
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('i18n/', include('django.conf.urls.i18n')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
import uuid
from abc import abstractmethod
from django.db import models
from django.utils import timezone
from django.urls import reverse
from tinymce import models as tinymce_models
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.contrib.auth.models import User


class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(default=timezone.now)
    last_modify_time = models.DateTimeField(default=timezone.now)

    class Meta:
        abstract = True

    @abstractmethod
    def get_absolute_url(self):
        pass


class Article(BaseModel):
    """
    Model for storing article data
    """
    STATUS_ARTICLE_CHOICES = [
        ("pe", "Pending"),
        ("pu", "Published"),
        ("re", "Rejected"),
    ]

    title = models.CharField(verbose_name=_('Title'),
                             max_length=100,
                             unique=True)
    body = tinymce_models.HTMLField()
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    category = models.ForeignKey('Category',
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 blank=True)
    image = models.ImageField(upload_to='article_img',
                              null=True, blank=True,
                              default='article_img/default_article.svg')
    status = models.CharField(max_length=2,
                              choices=STATUS_ARTICLE_CHOICES,
                              default='pe')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def get_absolute_url(self):
        return reverse('article:article_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"
        db_table_comment = "Article table braviss"
        get_latest_by = 'created_at'

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Category(BaseModel):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30, blank=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def get_absolute_url(self):
        return reverse('article:category_detail', kwargs={'category_name': self.slug})

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

article/views.py
from django.views.generic import (
    ListView,
    TemplateView,
    DetailView,
)
from article.models import Article
from view_breadcrumbs import (
    ListBreadcrumbMixin,
    DetailBreadcrumbMixin,
)
from django.contrib.auth.mixins import LoginRequiredMixin


class HomePageView(TemplateView):
    template_name = 'home.html'


class ArticleListView(LoginRequiredMixin, ListBreadcrumbMixin, ListView):
    model = Article
    template_name = 'article_list.html'
    context_object_name = 'articles'
    paginate_by = 10

    def get_queryset(self):
        return Article.objects.filter(status='pu').order_by('-created_at')


class ArticleDetailView(LoginRequiredMixin, DetailBreadcrumbMixin, DetailView):
    model = Article
    breadcrumb_use_pk = False
    template_name = 'article_detail.html'
    count_hit = True

    def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object()
        obj.viewed()
        self.object = obj
        return obj

templates/article_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
    <div class="card mb-3">
        <img class="card-img-top" src="{{ object.image.url }}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{ object.title }}</h5>
            <p class="card-text">{{ object.body|safe }}</p>
            <p class="card-text"><small class="text-muted">{{ object.created_at|date:"d.m.Y" }}</small></p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
                Поделиться
            </button>
        </div>
    </div>
    {# Modal share article#}
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Share {{ object.title }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Share link</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                               value="https://qtask.space{{ article.get_absolute_url }}">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/article_list.html
{% extends 'base.html' %}
{% load i18n %}


{% block title %}Article List{% endblock title %}

{% block content %}
    {% for article in articles %}
        <div class="card mb-4">
            <img class="card-img-top" src="{{ article.image.url }}">
            <div class="card-body">
                <h5 class="card-title">{{ article.title }}</h5>
                <p class="card-text">{{ article.body|truncatewords:20|safe }}</p>
                <a href="{{ article.get_absolute_url }}" class="btn btn-primary">Просмотр</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html
{% load i18n %}
{% load static %}
{% load view_breadcrumbs %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}QTASK{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
<div class="container">
    <a class="navbar-brand" href="#">ADEARN</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">{% trans 'Home' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'article:article_list' %}">{% trans 'Articles' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="">{% trans 'Tasks' %}</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
            {# Dropdown account link #}
            <ul class="navbar-nav">
                <li class="nav-item dropdown btn btn-primary dropdown-toggle mr-2">
                    <a class="nav-link dropdown-toggle p-0 text-white" href="/" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="">
                                {% trans 'Profile' %}
                                <i class="bi bi-person"></i>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="">
                                {% trans 'My article' %}
                                <i class="bi bi-folder"></i>
                            </a>
                        </li>
                        <li>
                            <div class="dropdown-divider"></div>
                            <form method="post" action="">
                                {% csrf_token %}
                                <input type="submit" value="{% trans 'Logout' %}" class="dropdown-item">
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
            {# Button login and register #}
        {% else %}
{#            <a href="{% url 'accounts:login' %}" class="btn btn-primary mr-2">{% trans 'Login' %}</a>#}
{#            <a href="{% url 'accounts:register' %}" class="btn btn-primary mr-2">{% trans 'Register' %}</a>#}
        {% endif %}
        {# Dropdown languages #}
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle p-0" style="height: 35px;" href="/" id="navbarDropdown" role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    {% if request.LANGUAGE_CODE == 'uk' %}
                        <img src="{% static 'icons/ua.svg' %}" alt="" style="height: 35px;">
                    {% else %}
                        <img src="{% static 'icons/um.svg' %}" alt="" style="height: 35px;">
                    {% endif %}
                </a>
                <form action="{% url 'set_language' %}" method="post" id="lang_form">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <li>
                                <button type="submit" name="language" value="{{ language.code }}"
                                        class="{% if language.code == LANGUAGE_CODE %}selected{% else %}demo-text-black{% endif %} dropdown-item">
                                    {{ language.name_local }}
                                </button>
                            </li>
                        {% endfor %}
                    </ul>
                </form>
                </a>
            </li>
        </ul>
    </div>
</div>
</nav>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            {% block breadcrumbs %}
                {% render_breadcrumbs %}
            {% endblock %}
            {% block content %}
            {% endblock content %}
        </div>
        <aside class="col-md-4 blog-sidebar">
            <div class="p-3 mb-3 bg-light rounded">
                <h4 class="font-italic">About</h4>
                <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus
                    sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            </div>
        </aside>
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
    <h1>Hello QTASK</h1>
{% endblock content %}